receivers:
  otlp:
    protocols:
      # files-services, auth-service use grpc otel exporter
      grpc: 
        endpoint: 0.0.0.0:4317
      # frontend use http otel exporter
      http: 
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ${ALLOWED_ORIGINS}

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
